### DISCUSSION TITLE
Can workflows be used also to generate images and sound from OpenAI models

### DISCUSSION THREAD

**Discussion by kiil** [llm-workflow-engine/llm-workflow-engine#328] [Q&A] [answered]
`lwe` is great and the ansible playbook workflows are *very* useful.

I am trying to find out whether these workflows are limited to "llm's" or if other kinds of generation can be invoked.

One use case for a workflow could be:

1. first to generate some text,
2. and then, based on the generated text, generate an accompanying image
3. and then further a text-to-speech sound file based also on the text

All this could then be saved to the same folder and ready for deployment to a website, for example.

Is that currently possible and if so, how?

Thank you.

**Comment by thehunmonkgroup** [comment, marked as answer]
There is not currently specific integration with non-text generations, however, the beauty of Ansible is that it's quite easy to add your own if you so desire. Possible approaches off the top of my head:

1. Call a custom Python script as a playbook task
2. Write a custom Ansible module

Below is some boilerplate for approach number one that GPT-4 whipped up, which shows how to invoke a custom script with an argument, and how to construct the script:

Ansible Playbook:
```yaml
---
- name: Call Python script with a customizable argument
  hosts: localhost
  vars:
    script_path: "/path/to/your/script.py"
    argument: "example_argument"

  tasks:
    - name: Execute Python script with an argument
      command: "python3 {{ script_path }} {{ argument }}"
      register: script_output

    - name: Show URL from Python script
      debug:
        msg: "The URL returned by the Python script is: {{ script_output.stdout }}"
```

Python Script (`script.py`):
```python
#!/usr/bin/env python3
import sys

# Get the argument from the command line
argument = sys.argv[1] if len(sys.argv) > 1 else "default"

# Construct the URL
url = f"http://www.example.com/{argument}"

# Output the URL
print(url)
```

Inside the Python script, you might use something like https://python.langchain.com/docs/integrations/tools/dalle_image_generator to do the work for image generation, as an example.
