### DISCUSSION TITLE
Is there a way I can change the OpenAI endpoint URL?

### DISCUSSION THREAD

**Discussion by ForeverNooob** [llm-workflow-engine/llm-workflow-engine#343] [Q&A] [answered]
Hello,

I might be misreading the docs, but I'm not sure how to configure this.

I want to use a service called ConvoAI, they have an OpenAI-compatible API endpoint which is this: `https://api.convoai.tech/v1/`

And then all I have to do is set my API key.

The thing is... I can't find a place where I can change the default OpenAI API URL endpoint (which I think is `https://api.openai.com/v1/chat`) to the one for ConvoAI.

Thanks in advance!

**Comment by thehunmonkgroup** [comment, marked as answer]
Most commands in LWE support tab completion.

`/model [TAB]` will show you all available options you can set on a particular provider. 

The default `chat_openai` provider has options for setting both base url and api key.

Once you set those in the CLI, you can save those settings as a preset.

**Reply by ForeverNooob** [reply]
`/model openai_api_base https://api.convoai.tech/v1/` - Yep, this did the trick, thanks!

Though I got some error afterwards, but I'm not sure whether these two events are related: https://github.com/llm-workflow-engine/llm-workflow-engine/issues/265#issuecomment-2079158084

**Comment by thehunmonkgroup** [comment]
#265 has nothing to do with it.

The error is occurring in the thread that generates the title.

By default LWE uses OpenAI's GPT-3.5 to generate a short title for all conversations. If you don't have a valid `OPENAI_API_KEY` environment variable set for the OpenAI API, this would throw an error. My assumption is you have that environment variable set to the API key for convoai.

There is a config setting `backend_options.title_generation.provider` that allows you to override using the `chat_openai` provider to generate titles, but you'd need to set up another provider for that.

Given the proliferation of OpenAI compatible endpoints, it's probably best to add a `backend_options.title_generation.preset` config setting, which you could set to a configured preset to use whatever provider/model you want for title generation.

**Comment by thehunmonkgroup** [comment]
I took a look at adding `backend_options.title_generation.preset`, and it's just going to be too messy given the architecture of the code.

Probably the cleanest and easiest option for you is to set `openai_api_key` in your preset to the convoai API key, and set `OPENAI_API_KEY` environment variable to a valid OpenAI API key.

You could also use `backend_options.title_generation.provider` to use a different provider, I did add some doc on that setting: https://github.com/llm-workflow-engine/llm-workflow-engine/blob/main/config.sample.yaml#L24-L28

LWE has quite a few other providers: https://github.com/orgs/llm-workflow-engine/repositories?q=provider

Finally, if you just want to go w/o titles, this will work to suppress the error:

Adjust config as follows:

```yaml
backend_options:
  title_generation:
    provider: fake_llm
plugins:
  enabled:
    - provider_fake_llm
```

That's the testing class, and will just title everything `test response`.

**Reply by ForeverNooob** [reply]
Thanks! I chose to go without titles because I prefer to set my own, but despite that I'm still getting that error.

This is inside my `~/.config/llm-workflow-engine/config.yaml`:
```yaml
backend: api
backend_options:
  auto_create_first_user: None
  default_user: None
  default_conversation_id: None
  title_generation:
    provider: fake_llm

plugins:
  enabled:
    - echo
    - examples
    - provider_fake_llm
```

```
└─$  lwe --version
/home/me/.local/bin/lwe version 0.18.11
```

**Comment by thehunmonkgroup** [comment]
It's working fine for me:

```yaml
backend_options:
  title_generation:
    provider: fake_llm
# other settings...
plugins:
  enabled:
    - provider_fake_llm
```

```
[New Conversation]
(0.5/204800/0): default
hunmonk@claude-chatbot-responses 10> say hello

Hello! How can I assist you today?

[Untitled]
(0.5/204800/20): default
hunmonk@claude-chatbot-responses 11>
test response
(0.5/204800/20): default
hunmonk@claude-chatbot-responses 11>
```

You can see the `test response` title generated from the fake_llm provider.

Are you sure it's the same error, or is it another error? Have you run LWE with the debug flag and compared the backtrace?
